spring:
  application:
    name: 1khm
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123321
    url: jdbc:postgresql://localhost:5432/one_khm
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  token:
    secret:
      key: aGkgbXkgbmFtZSBpcyBCRUhaT0QgaSBhbSBqYXZhIGRldmVsb3BlciA=
      expiry: 2_628_000_000