spring:
  application:
    name: 1khm
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: <your_password>
    url: jdbc:postgresql://localhost:5432/one_khm
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update